name: whosthat
description: "A game that lets kids guess which family member"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  permission_handler: ^11.3.1
  flutter_tts: ^4.2.0
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  confetti: ^0.8.0
  tutorial_coach_mark: ^1.2.12
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/
